fail_fast: false
exclude:
  (?x)^( docs/ | another/example/directory/to_exclude/ | example/file/to_exclude\.py | another/example/file/to_exclude\.py )
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: fix-byte-order-marker
      - id: mixed-line-ending
        args: [--fix=lf]

  - repo: https://github.com/pycqa/isort
    rev: 5.13.2
    hooks:
      - id: isort
        name: isort (python)

  - repo: https://github.com/psf/black
    rev: 24.10.0
    hooks:
      - id: black
        args: ["--line-length", "119"]

  - repo: https://github.com/codespell-project/codespell
    rev: v2.4.0
    hooks:
      - id: codespell
        args: [--ignore-words=.dictionary.txt, -w]

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.6.2
    hooks:
      - id: prettier
        types_or: [css, javascript, html, yaml, json, markdown]

  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v8.16.0
    hooks:
      - id: eslint
        additional_dependencies: [eslint@8.15.0, eslint-config-prettier@8.5.0, eslint-plugin-no-unsanitized@4.0.1]
        args: [--fix]

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-json
      - id: check-yaml
        fail_fast: true # applies to check-yaml as well as every hook below
      - id: name-tests-test
      - id: no-commit-to-branch
        stages: [commit]

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.9.6
    hooks:
      - id: ruff
        args: [--fix]

  - repo: local
    hooks:
      - id: restructuredtext_lint
        # exclude docs src because that is sphinx rst not normal rst
        exclude: ^docs-src/
        name: rst lint
        entry: rst-lint --encoding utf-8
        additional_dependencies: [restructuredtext_lint]
        types: [rst]
        language: python

  - repo: https://github.com/PyCQA/doc8
    rev: v1.1.2
    hooks:
      - id: doc8
        args: ["--max-line-length", "119", "--file-encoding", "utf-8"]

  - repo: https://github.com/markdownlint/markdownlint
    rev: v0.11.0
    hooks:
      - id: markdownlint

  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.10
    hooks:
      - id: bandit
        args: [--severity-level=high, --confidence-level=high]

  - repo: https://github.com/awebdeveloper/pre-commit-stylelint
    rev: 0.0.2
    hooks:
      - id: stylelint
        additional_dependencies: [stylelint@14.8.2, stylelint-config-standard@25.0.0, stylelint-config-prettier@9.0.3]

  - repo: https://github.com/Lucas-C/pre-commit-hooks-java
    rev: 1.3.10
    hooks:
      - id: validate-html
        exclude: ^tests/
        name: html validate

  - repo: https://github.com/Lucas-C/pre-commit-hooks-safety
    rev: v1.3.3
    hooks:
      - id: python-safety-dependencies-check
        files: requirements.txt

  - repo: https://github.com/streetsidesoftware/cspell-cli
    rev: v6.0.0
    hooks:
      - id: cspell
        args: [--config, .cspell.yaml, --no-summary, --gitignore, --no-progress]
        types_or: [css, javascript, html]
